import type { Task } from "@/types/task";

export const initialTasks = [
  {
    id: "task-001",
    title: "Finalize launch checklist",
    description: "Confirm owner sign-off, rollback plan, and release communications before launch.",
    status: "in-progress",
    priority: "urgent",
    project: "Launch Operations",
    assignee: {
      id: "user-maya-chen",
      name: "Maya Chen",
      avatarInitials: "MC",
    },
    tags: ["launch", "operations", "checklist"],
    dueDate: "2026-05-07",
    createdAt: "2026-05-01T09:00:00.000Z",
    updatedAt: "2026-05-06T16:30:00.000Z",
  },
  {
    id: "task-002",
    title: "Review dashboard analytics copy",
    description: "Polish metric labels and helper copy so dashboard insights are clear for beta users.",
    status: "review",
    priority: "high",
    project: "Dashboard Experience",
    assignee: {
      id: "user-noah-patel",
      name: "Noah Patel",
      avatarInitials: "NP",
    },
    tags: ["dashboard", "copy", "analytics"],
    dueDate: "2026-05-08",
    createdAt: "2026-05-02T10:15:00.000Z",
    updatedAt: "2026-05-06T14:10:00.000Z",
  },
  {
    id: "task-003",
    title: "Triage priority customer feedback",
    description: "Group onboarding feedback by severity and identify follow-up tasks for the next sprint.",
    status: "todo",
    priority: "high",
    project: "Customer Insights",
    assignee: {
      id: "user-olivia-rivera",
      name: "Olivia Rivera",
      avatarInitials: "OR",
    },
    tags: ["feedback", "customers", "planning"],
    dueDate: "2026-05-09",
    createdAt: "2026-05-03T13:45:00.000Z",
    updatedAt: "2026-05-05T11:20:00.000Z",
  },
  {
    id: "task-004",
    title: "Prepare mobile QA pass",
    description: "Validate sidebar drawer, top navigation, and dashboard cards across common mobile widths.",
    status: "in-progress",
    priority: "medium",
    project: "Quality Assurance",
    assignee: {
      id: "user-ethan-brooks",
      name: "Ethan Brooks",
      avatarInitials: "EB",
    },
    tags: ["mobile", "qa", "responsive"],
    dueDate: "2026-05-12",
    createdAt: "2026-05-04T08:30:00.000Z",
    updatedAt: "2026-05-06T09:40:00.000Z",
  },
  {
    id: "task-005",
    title: "Document task filtering requirements",
    description: "Outline filter states for status, priority, search, and due-date views before implementation.",
    status: "todo",
    priority: "medium",
    project: "Task Management",
    assignee: {
      id: "user-sophia-lee",
      name: "Sophia Lee",
      avatarInitials: "SL",
    },
    tags: ["filters", "requirements", "tasks"],
    dueDate: "2026-05-14",
    createdAt: "2026-05-04T12:00:00.000Z",
    updatedAt: "2026-05-04T12:00:00.000Z",
  },
  {
    id: "task-006",
    title: "Archive completed sprint notes",
    description: "Move final sprint decisions into the shared workspace and link them from the roadmap.",
    status: "done",
    priority: "low",
    project: "Team Operations",
    assignee: {
      id: "user-maya-chen",
      name: "Maya Chen",
      avatarInitials: "MC",
    },
    tags: ["documentation", "sprint", "archive"],
    dueDate: "2026-05-05",
    createdAt: "2026-04-29T15:20:00.000Z",
    updatedAt: "2026-05-05T10:00:00.000Z",
    completedAt: "2026-05-05T10:00:00.000Z",
  },
] as const satisfies readonly Task[];
